<a href="https://colab.research.google.com/github/hector2506/aprendizado-pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors with Pytorch

Tensors são como Numpy Arrays, mas mais poderosos e próprios para Deep Learning.

Eles são por padrão float32, mas podem ser alterados para float64.

Documentação: https://pytorch.org/docs/stable/tensors.html

In [12]:
import torch
import numpy as np

## Lists

In [1]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

## Numpy Arrays

In [10]:
np1 = np.random.rand(3,4)
np1.dtype
np1

array([[0.71006761, 0.30695316, 0.77477798, 0.45124504],
       [0.94662666, 0.45608469, 0.20941542, 0.80392481],
       [0.22178783, 0.60649346, 0.23328309, 0.91193494]])

## Tensors

In [7]:
tensor_2d = torch.randn(3, 4)
tensor_2d
#tensor_2d.dtype

tensor([[-1.0798,  1.2125,  0.8382,  0.4603],
        [ 0.0447,  1.2719, -0.5355,  1.1191],
        [-0.0366, -1.4016,  0.0124,  0.8890]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## Create tensor out of numpy array

In [11]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7101, 0.3070, 0.7748, 0.4512],
        [0.9466, 0.4561, 0.2094, 0.8039],
        [0.2218, 0.6065, 0.2333, 0.9119]], dtype=torch.float64)