<a href="https://colab.research.google.com/github/hector2506/aprendizado-pytorch/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Math Operations

In [1]:
import torch
import numpy as np

In [4]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

## Addition

In [5]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
# Addition Function
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [17]:
# Addition function alternative
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

## Subtract

In [9]:
# Subtraction Shorthand
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [8]:
# Subtraction Function
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

## Multiply

In [10]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [11]:
# Multiplication Function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

## Divide

In [12]:
# Division
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [13]:
# Division Function
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

## Remainders

In [14]:
# Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
# Remainder Function
torch.remainder(tensor_b,tensor_a)

## Exponents

In [15]:
# Exponent
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [16]:
# Exponent Function
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

## Reassignment

In [22]:
# Reassignment
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [23]:
tensor_a

tensor([ 6,  8, 10, 12])